# Generated by Django 5.1.4 on 2024-12-10 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVerity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 12, 10, 10, 47, 2, 526726, tzinfo=datetime.timezone.utc))),
                ('chai_type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('PL', 'PLAIN'), ('EL', 'ELACHI'), ('LE', 'LEMON')], max_length=2)),
            ],
        ),
    ]
