# Generated by Django 5.1.4 on 2024-12-10 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 10, 47, 28, 624410, tzinfo=datetime.timezone.utc)),
        ),
    ]
